name: twitter-graph
version: 2
services:

  importer:
    image: jakolehm/twitter-graph-neo4j-importer:latest
    #build:
    #  context: twitter-import/
    command: python /import_user.py $TWITTER_USER
    secrets:
      - secret: TWITTER_GRAPH_NEO4J_PASSWORD
        name: NEO4J_PASSWORD
        type: env
      - secret: TWITTER_GRAPH_CONSUMER_KEY
        name: TWITTER_CONSUMER_KEY
        type: env
      - secret: TWITTER_GRAPH_CONSUMER_SECRET
        name: TWITTER_CONSUMER_SECRET
        type: env
      - secret: TWITTER_GRAPH_USER_KEY
        name: TWITTER_USER_KEY
        type: env
      - secret: TWITTER_GRAPH_USER_SECRET
        name: TWITTER_USER_SECRET
        type: env
    environment:
      - NEO4J_HOST=%{project}-neo-1
    depends_on:
      - neo

  neo:
    image: jakolehm/twitter-graph-neo4j:2.3-enterprise
    #build:
    #  context: neo4j/
    stateful: true
    instances: 1
    deploy:
      wait_for_port: 7474
    secrets:
      - secret: TWITTER_GRAPH_NEO4J_AUTH
        name: NEO4J_AUTH
        type: env
    environment:
      KONTENA_LB_INTERNAL_PORT: 7474
      KONTENA_LB_VIRTUAL_PATH: /
      KONTENA_LB_BALANCE: source
      #NEO4J_DATABASE_MODE: HA
      #NEO4J_INITIAL_HOSTS: %{project}-neo-1,%{project}-neo-2,%{project}-neo-3
      #KONTENA_LB_CUSTOM_SETTINGS: |
      #  option httpchk HEAD /db/manage/server/ha/master HTTP/1.0\r\nAuthorization:\ Basic\ bmVvNGo6c2VjcmV0eno=
    links:
      - lb

  lb:
    image: kontena/lb:latest
    deploy:
      strategy: daemon
    ports:
      - 80:80
